# Generated by Django 4.2.10 on 2024-02-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programming',
            name='type_of_project',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
